apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: go-service-ci-run-
spec:
  pipelineRef:
    name: go-service-ci
  params:
    - name: repo-url
      value: https://github.com/irvnet/go-tekton-mservice.git
    - name: revision
      value: main
    - name: image-url
      value: docker.io/irvnet/go-tekton-mservice:latest
  workspaces:
    - name: output
      emptyDir: {}

